/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Clases.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author johnd
 */
public class MainInterfaz extends javax.swing.JFrame {

    public static Administrador admin;
    public static IA ia;
    public static Cola cola_1_john;
    public static Cola cola_2_john;
    public static Cola cola_3_john;
    public static Cola cola_refuerzo_john;
    public static Cola cola_1_ale;
    public static Cola cola_2_ale;
    public static Cola cola_3_ale;
    public static Cola cola_refuerzo_ale;
    public static boolean encendido;
    public static int contador;
    public static String [] tipo_material;
    public static int [] cartas;
    public static int ID_global;
    public static int vendidos_john;
    public static int vendidos_ale;
    
    
    
    /**
     * Creates new form MainInterfaz
     */
    public MainInterfaz() {
        initComponents();
        this.setResizable(false);
        this.setVisible(true);
        this.setSize(800,700);
        this.setLocationRelativeTo(null);
        this.admin= new Administrador();
        this.ia= new IA();
        this.cola_1_john= new Cola();
        this.cola_2_john= new Cola();
        this.cola_3_john= new Cola();
        this.cola_refuerzo_john= new Cola();
        this.cola_1_ale= new Cola();
        this.cola_2_ale= new Cola();
        this.cola_3_ale= new Cola();
        this.cola_refuerzo_ale= new Cola();
        this.encendido=false;
        this.contador=0;
        this.tipo_material= new String[4];
        this.cartas= new int[8];
        this.ID_global=0;
        this.vendidos_john=0;
        this.vendidos_ale=0;
        
        tipo_material[0]="Madera";
        tipo_material[1]="Aluminio";
        tipo_material[2]="Oro";
        tipo_material[3]="Diamante";
        cartas[0]=1;
        cartas[1]=2;
        cartas[2]=3;
        cartas[3]=4;
        cartas[4]=5;
        cartas[5]=6;
        cartas[6]=7;
        cartas[7]=8;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menos = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cola1john = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        colarefuerzojohn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        cola2ale = new javax.swing.JTextField();
        cola3ale = new javax.swing.JTextField();
        colarefuerzoale = new javax.swing.JTextField();
        cola3john = new javax.swing.JTextField();
        cola2john = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tiempo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ganador = new javax.swing.JTextField();
        cola1ale = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();
        carta81 = new javax.swing.JLabel();
        carta82 = new javax.swing.JLabel();
        carta71 = new javax.swing.JLabel();
        carta72 = new javax.swing.JLabel();
        carta61 = new javax.swing.JLabel();
        carta62 = new javax.swing.JLabel();
        carta51 = new javax.swing.JLabel();
        carta52 = new javax.swing.JLabel();
        carta41 = new javax.swing.JLabel();
        carta42 = new javax.swing.JLabel();
        carta31 = new javax.swing.JLabel();
        carta32 = new javax.swing.JLabel();
        carta21 = new javax.swing.JLabel();
        carta22 = new javax.swing.JLabel();
        carta11 = new javax.swing.JLabel();
        carta12 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/menos.png"))); // NOI18N
        menos.setBorderPainted(false);
        menos.setContentAreaFilled(false);
        jPanel1.add(menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 40, 30));

        mas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/mas.png"))); // NOI18N
        mas.setBorderPainted(false);
        mas.setContentAreaFilled(false);
        mas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 600, 40, 30));

        cola1john.setEditable(false);
        jScrollPane1.setViewportView(cola1john);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 40, 160));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("|");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 54, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PLANTA 2: ALE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 380, 67));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REFUERZO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 80, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("|");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 54, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("|");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 54, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("|");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 54, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("|");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 54, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("|");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 54, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("|");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 54, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/estadisticas.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 50, 50));

        colarefuerzojohn.setEditable(false);
        colarefuerzojohn.setBackground(new java.awt.Color(204, 204, 204));
        colarefuerzojohn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        colarefuerzojohn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colarefuerzojohn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colarefuerzojohnActionPerformed(evt);
            }
        });
        jPanel1.add(colarefuerzojohn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 40, 160));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("|");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 54, -1));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 140, 30));

        cola2ale.setEditable(false);
        cola2ale.setBackground(new java.awt.Color(204, 204, 204));
        cola2ale.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cola2ale.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cola2ale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cola2aleActionPerformed(evt);
            }
        });
        jPanel1.add(cola2ale, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 40, 160));

        cola3ale.setEditable(false);
        cola3ale.setBackground(new java.awt.Color(204, 204, 204));
        cola3ale.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cola3ale.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cola3ale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cola3aleActionPerformed(evt);
            }
        });
        jPanel1.add(cola3ale, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 40, 160));

        colarefuerzoale.setEditable(false);
        colarefuerzoale.setBackground(new java.awt.Color(204, 204, 204));
        colarefuerzoale.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        colarefuerzoale.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colarefuerzoale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colarefuerzoaleActionPerformed(evt);
            }
        });
        jPanel1.add(colarefuerzoale, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 40, 160));

        cola3john.setEditable(false);
        cola3john.setBackground(new java.awt.Color(204, 204, 204));
        cola3john.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cola3john.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cola3john.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cola3johnActionPerformed(evt);
            }
        });
        jPanel1.add(cola3john, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 40, 160));

        cola2john.setEditable(false);
        cola2john.setBackground(new java.awt.Color(204, 204, 204));
        cola2john.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cola2john.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cola2john.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cola2johnActionPerformed(evt);
            }
        });
        jPanel1.add(cola2john, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 40, 160));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("COLA 1");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 80, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/boton-de-apagado.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, 50, 50));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("COLA 3");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 80, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/boton-de-encendido.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, 50, 50));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("REFUERZO");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 80, 30));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("GANADOR");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 150, 40));

        tiempo.setEditable(false);
        tiempo.setBackground(new java.awt.Color(204, 204, 204));
        tiempo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        tiempo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoActionPerformed(evt);
            }
        });
        jPanel1.add(tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, 80, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PLANTA 1: JOHN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 390, 63));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("COLA 1");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("INTELIGENCIA ARTIFICIAL");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 190, 30));

        ganador.setEditable(false);
        ganador.setBackground(new java.awt.Color(255, 255, 255));
        ganador.setForeground(new java.awt.Color(0, 0, 0));
        ganador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ganador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganadorActionPerformed(evt);
            }
        });
        jPanel1.add(ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 150, 30));

        cola1ale.setEditable(false);
        cola1ale.setBackground(new java.awt.Color(204, 204, 204));
        cola1ale.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        cola1ale.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cola1ale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cola1aleActionPerformed(evt);
            }
        });
        jPanel1.add(cola1ale, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 40, 160));

        jTextField11.setBackground(new java.awt.Color(255, 51, 51));
        jTextField11.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 60, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("COLA 3");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 80, 30));

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(204, 204, 204));
        jTextField13.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 140, 30));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("TIEMPO");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, 60, 30));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("ADMINISTRADOR");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 130, 30));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("COLA 2");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 80, 30));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("COLA 2");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 80, 30));

        fondo1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fondo1.setForeground(new java.awt.Color(255, 255, 255));
        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Diseño sin título (16).png"))); // NOI18N
        fondo1.setText("COLA 2");
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, 120));

        fondo2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fondo2.setForeground(new java.awt.Color(255, 255, 255));
        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Diseño sin título (16).png"))); // NOI18N
        fondo2.setText("COLA 2");
        fondo2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, 120));

        carta81.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta81.setForeground(new java.awt.Color(255, 255, 255));
        carta81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/1.png"))); // NOI18N
        carta81.setText("COLA 2");
        jPanel1.add(carta81, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, 120));

        carta82.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta82.setForeground(new java.awt.Color(255, 255, 255));
        carta82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/1.png"))); // NOI18N
        carta82.setText("COLA 2");
        carta82.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(carta82, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, 120));

        carta71.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta71.setForeground(new java.awt.Color(255, 255, 255));
        carta71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/2.png"))); // NOI18N
        carta71.setText("COLA 2");
        jPanel1.add(carta71, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, 120));

        carta72.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta72.setForeground(new java.awt.Color(255, 255, 255));
        carta72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/2.png"))); // NOI18N
        carta72.setText("COLA 2");
        carta72.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(carta72, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, 120));

        carta61.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta61.setForeground(new java.awt.Color(255, 255, 255));
        carta61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/3.png"))); // NOI18N
        carta61.setText("COLA 2");
        jPanel1.add(carta61, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, 120));

        carta62.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta62.setForeground(new java.awt.Color(255, 255, 255));
        carta62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/3.png"))); // NOI18N
        carta62.setText("COLA 2");
        carta62.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(carta62, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, 120));

        carta51.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta51.setForeground(new java.awt.Color(255, 255, 255));
        carta51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/4.png"))); // NOI18N
        carta51.setText("COLA 2");
        jPanel1.add(carta51, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, 120));

        carta52.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta52.setForeground(new java.awt.Color(255, 255, 255));
        carta52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/4.png"))); // NOI18N
        carta52.setText("COLA 2");
        carta52.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(carta52, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, 120));

        carta41.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta41.setForeground(new java.awt.Color(255, 255, 255));
        carta41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/5.png"))); // NOI18N
        carta41.setText("COLA 2");
        jPanel1.add(carta41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, 120));

        carta42.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta42.setForeground(new java.awt.Color(255, 255, 255));
        carta42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/5.png"))); // NOI18N
        carta42.setText("COLA 2");
        carta42.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(carta42, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, 120));

        carta31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta31.setForeground(new java.awt.Color(255, 255, 255));
        carta31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/6.png"))); // NOI18N
        carta31.setText("COLA 2");
        jPanel1.add(carta31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, 120));

        carta32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta32.setForeground(new java.awt.Color(255, 255, 255));
        carta32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/6.png"))); // NOI18N
        carta32.setText("COLA 2");
        carta32.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(carta32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, 120));

        carta21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta21.setForeground(new java.awt.Color(255, 255, 255));
        carta21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/7.png"))); // NOI18N
        carta21.setText("COLA 2");
        jPanel1.add(carta21, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, 120));

        carta22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta22.setForeground(new java.awt.Color(255, 255, 255));
        carta22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/7.png"))); // NOI18N
        carta22.setText("COLA 2");
        carta22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(carta22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, 120));

        carta11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta11.setForeground(new java.awt.Color(255, 255, 255));
        carta11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/8.png"))); // NOI18N
        carta11.setText("COLA 2");
        jPanel1.add(carta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 90, 120));

        carta12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carta12.setForeground(new java.awt.Color(255, 255, 255));
        carta12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Cartas/8.png"))); // NOI18N
        carta12.setText("COLA 2");
        carta12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(carta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 90, 120));

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(204, 204, 204));
        jTextField15.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 140, 60));

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(204, 204, 204));
        jTextField14.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 140, 60));

        jTextField16.setBackground(new java.awt.Color(51, 51, 255));
        jTextField16.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 60, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfazimg/newpackage/Diseño sin título (15).png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 810, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colarefuerzojohnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colarefuerzojohnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colarefuerzojohnActionPerformed

    private void cola2johnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cola2johnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cola2johnActionPerformed

    private void cola3johnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cola3johnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cola3johnActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void cola2aleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cola2aleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cola2aleActionPerformed

    private void cola3aleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cola3aleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cola3aleActionPerformed

    private void colarefuerzoaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colarefuerzoaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colarefuerzoaleActionPerformed

    private void cola1aleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cola1aleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cola1aleActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Borrar colas antes
        encendido=true;
        Telefono telf_john= new Telefono(0);
        Telefono telf_ale= new Telefono(1);
        Administrador.Agregartelf();
        
        try {
            IA.decision(telf_john, telf_ale);
            } catch (InterruptedException ex) {
            Logger.getLogger(MainInterfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        while (encendido!=false) {
            try {
                Administrador.Adminescoger();
            } catch (InterruptedException ex) {
                Logger.getLogger(MainInterfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        encendido=false;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void ganadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ganadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel carta11;
    public static javax.swing.JLabel carta12;
    public static javax.swing.JLabel carta21;
    public static javax.swing.JLabel carta22;
    public static javax.swing.JLabel carta31;
    public static javax.swing.JLabel carta32;
    public static javax.swing.JLabel carta41;
    public static javax.swing.JLabel carta42;
    public static javax.swing.JLabel carta51;
    public static javax.swing.JLabel carta52;
    public static javax.swing.JLabel carta61;
    public static javax.swing.JLabel carta62;
    public static javax.swing.JLabel carta71;
    public static javax.swing.JLabel carta72;
    public static javax.swing.JLabel carta81;
    public static javax.swing.JLabel carta82;
    public static javax.swing.JTextField cola1ale;
    private javax.swing.JTextPane cola1john;
    public static javax.swing.JTextField cola2ale;
    public static javax.swing.JTextField cola2john;
    public static javax.swing.JTextField cola3ale;
    public static javax.swing.JTextField cola3john;
    public static javax.swing.JTextField colarefuerzoale;
    public static javax.swing.JTextField colarefuerzojohn;
    public static javax.swing.JLabel fondo1;
    public static javax.swing.JLabel fondo2;
    public static javax.swing.JTextField ganador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jTextField11;
    public static javax.swing.JTextField jTextField13;
    public static javax.swing.JTextField jTextField14;
    public static javax.swing.JTextField jTextField15;
    public static javax.swing.JTextField jTextField16;
    public static javax.swing.JTextField jTextField6;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    public static javax.swing.JTextField tiempo;
    // End of variables declaration//GEN-END:variables
}
